### PR TITLE
Add Github Actions and tox with docs and pre-commit

### PR DESCRIPTION
**Pull request by gaborbernat**
A follow-up PR would be to add actual tests... Did some of this already in the past here https://github.com/gaborbernat/sphinx-autodoc-typehints/blob/master/tests/test_project_format.py#L20

Here's the run show would this be accepted it would actually pass https://github.com/gaborbernat/sphinxcontrib-towncrier/actions/runs/197400588

### CODE REVIEW

**Comment by webknjaz** [comment]
Ouch... This was supposed to be a learning experience for @slsh1o

**Comment by gaborbernat** [comment]
oh ok you want to reject the PR then?

**Comment by gaborbernat** [comment]
I'll retract back into my shell, and ignore this library for now then.

**Comment by webknjaz** [comment]
@gaborbernat thanks! I'll ping you once it's ready to be looked at.

**Comment by gaborbernat** [comment]
Please don't, I'm no longer interested in the project.

thanks

**Comment by webknjaz** [comment]
Sorry

**Comment by gaborbernat** [comment]
No worries ☺️

**Pull request closed without merging**
